In [1]:
%reload_ext autoreload
%autoreload 2
import pandas as pd
import glob
import pickle
from utilities import *
import numpy as np

In [3]:
payoffs = load_data('../model/data/processed/50yr_all2.pickle')

In [4]:
utilities = get_marginal_utility_of_df(payoffs)

In [26]:
def is_pareto_efficient_simple(costs):
    """
    Find the pareto-efficient points
    :param costs: An (n_points, n_costs) array
    :return: A (n_points, ) boolean array, indicating whether each point is Pareto efficient
    """
    is_efficient = np.ones(costs.shape[0], dtype = bool)
    for i, c in enumerate(costs):
        if is_efficient[i]:
            is_efficient[is_efficient] = np.any(costs[is_efficient]<c, axis=1)  # Keep any point with a lower cost
            is_efficient[i] = True  # And keep self
    return is_efficient

In [44]:
costs = np.array(payoffs)
is_efficient = np.ones(costs.shape[0], dtype = bool)
#print(is_efficient)
for i, c in enumerate(costs):
    #print(i)
    if is_efficient[i]:
        #if np.any(costs[is_efficient]<c) == True:
            #print(costs[is_efficient] > c)
        #print(np.any(costs[is_efficient]<c))
        is_efficient[is_efficient] = np.any(costs[is_efficient]<c, axis=1)  # Keep any point with a lower cost
        is_efficient[i] = True  # And keep self

In [64]:
np.array(payoffs)[51]

array([44.20553336,  0.66701461,  0.44865701,  0.59639553,  0.785     ,
       -0.29937163, -2.57760137])

In [71]:
np.array(payoffs)[23]>np.array(payoffs)[51]

array([ True,  True,  True,  True,  True,  True,  True])

In [70]:
(np.array(payoffs) > np.array(payoffs)[24])[:,0]==True

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
       False,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True])

In [27]:
is_pareto_efficient_simple(np.array(utilities))

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True, False,  True,  True,  True,
       False, False, False,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True])